---
name: Build (Vercel)
on:
  push:
    branches: [ 'main' ]
    
jobs:
  vercel_trigger:
    name: Vercel Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Hit the webhook
        run: curl $VERCEL_DEPLOY_HOOK
